# Generated by Django 6.0.3 on 2026-03-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
