# Generated by Django 6.0.3 on 2026-03-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_hr_user_is_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("java", "Java"),
                    ("python", "Python"),
                    ("php", "PHP"),
                    ("salesforce", "Salesforce"),
                    ("dynamics", "Dynamics"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
