# Generated by Django 6.0.3 on 2026-03-20 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('first_login', models.DateTimeField()),
                ('sign_off_time', models.DateTimeField(blank=True, null=True)),
                ('total_work_seconds', models.PositiveIntegerField(default=0)),
                ('work_mode', models.CharField(blank=True, choices=[('office', 'Work From Office'), ('home', 'Work From Home'), ('', 'Not Selected')], default='', max_length=20)),
                ('is_signed_off', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-work_date'],
                'unique_together': {('user', 'work_date')},
            },
        ),
    ]
